In [ ]:
Exercise 1

In [15]:
import numpy as np 

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

def addition(v1,v2):
    v3 = v1+v2 
    return v3

v3=addition(v1,v2)
print(v3)

[5 7 9]


In [16]:
import numpy as np 

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

def subtraction (v1,v2):
    v3 = v1-v2
    return v3
v3 = subtraction(v1,v2)
print (v3)
    

[-3 -3 -3]


In [22]:
import numpy as np 
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

def Dot(v1,v2):
    return np.dot(v1,v2)
v3 = Dot(v1,v2)
print (v3)

32


In [23]:
import numpy as np 
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

def cross(v1,v2):
  return np.cross(v1,v2)
v3 = cross(v1,v2)
print (v3)

[-3  6 -3]


In [27]:
import numpy as np
v = np.array([1,2,3])

magnitude = (sum(v**2))**0.5
print (magnitude)



3.7416573867739413


In [ ]:
Exercise 2

In [32]:
import numpy as np 
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

def matrix_addition(m1,m2):
    return m1+m2
m3 = matrix_addition(m1,m2)
print (m3)

[[ 6  8]
 [10 12]]


In [33]:
import numpy as np 
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

def matrix_subtraction(m1,m2):
    return m1-m2 
m3 = matrix_subtraction(m1,m2)
print (m3)

[[-4 -4]
 [-4 -4]]


In [36]:
import numpy as np 
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

def matrix_multiplication(m1,m2):
    return m1@m2
m3 = matrix_multiplication(m1,m2) 
print (m3)

[[19 22]
 [43 50]]


In [41]:
import numpy as np 

m1 = np.array([[1, 2], [3, 4]])

def matrix_transpose(m1):
    return np.transpose(m1)

m3 = matrix_transpose(m1)
print(m3)

[[1 3]
 [2 4]]


In [43]:
import numpy as np 
m1 = np.array([[1, 2], [3, 4]])

def matrix_determinant(m1):
    return np.linalg.det(m1)
m3 =  matrix_determinant(m1)
print (m3)

-2.0000000000000004


In [ ]:
Exercise 3

In [47]:
import numpy as np 
v1 = np.array([1,2,3])
v2= np.array([4,5,6])
v= np.array([1,0])

scalar=2.5
def scale_vector(v1,scalar):
    return v1 * scalar
result = scale_vector(v1,scalar)
print (result)


[2.5 5.  7.5]


In [ ]:
import numpy as np 
v1 = np.array([1,2,3])
v2= np.array([4,5,6])

def angle_between(v1,v2):
    dot_prod = np.dot(v1,v2)
    